name: aip_tracker
description: The Malawi AIP Tracker - Building A Nation Of Self-Reliant Farmers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  # State Management
  provider: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Utilities
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

   assets:
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/farmers/
    - assets/images/distributors/
    - assets/images/vasps/
    - assets/images/admin/
    - assets/fonts/
    - assets/illustrations/

  
